"""add settings and password security

Revision ID: 0161decd8ffb
Revises: c84f05d92410
Create Date: 2026-08-10 10:27:58.047066

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '0161decd8ffb'
down_revision = 'c84f05d92410'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('password_reset_tokens',
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('jti_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_password_reset_tokens_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_password_reset_tokens'),
    sa.UniqueConstraint('jti_hash', name='uq_password_reset_tokens_jti_hash')
    )
    op.create_index('ix_password_reset_tokens_expires_at', 'password_reset_tokens', ['expires_at'])
    op.create_index('ix_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'])

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), server_default='America/Mexico_City', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_version', sa.Integer(), server_default='0', nullable=False))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth_version')

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('phone')

    op.drop_index('ix_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_expires_at', table_name='password_reset_tokens')

    op.drop_table('password_reset_tokens')
