"""Ampliar longitud de password

Revision ID: 21deb61cd0f2
Revises: fc487e1d9f6b
Create Date: 2026-07-29 13:09:41.009952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21deb61cd0f2'
down_revision = 'fc487e1d9f6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)

    # ### end Alembic commands ###
