"""Permitir google_id nulo

Revision ID: 92f7e2238b29
Revises: 7364b830a5b0
Create Date: 2026-08-02 16:45:09.883123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f7e2238b29'
down_revision = '7364b830a5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_picture',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
