"""Ajuste modelos

Revision ID: 93ed3045170e
Revises: b4e2c8a91d73
Create Date: 2026-08-06 10:55:42.824441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ed3045170e'
down_revision = 'b4e2c8a91d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['public_id'])
        batch_op.drop_constraint(batch_op.f('catalogue_business_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'business', ['business_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('catalogue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('catalogue_business_id_fkey'), 'business', ['business_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('published_at')
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
