import { BarChart3, BookOpen, Box, PackagePlus, Plus, QrCode } from "lucide-react";
import { Link } from "react-router";
import { useTranslation } from "react-i18next";
import { formatNumber as intlNumber } from "../../../i18n/formats";

const formatNumber = (value) => value === null || value === undefined ? "—" : intlNumber(value);

export function MetricCard({ title, value, detail, icon: Icon, tone = "yellow", titleHint }) {
  const { t } = useTranslation();
  const toneClass = tone === "cream" ? "bg-[#F8E8AE]" : tone === "sand" ? "bg-[#E9DDB7]" : "bg-[#FFE05A]";
  return <article className="min-h-36 rounded-2xl border border-[#D9D9D9] bg-[#FFFDF5] p-[18px]"><div className="flex items-start justify-between gap-3"><p title={titleHint ? t(titleHint) : undefined} className="text-xs font-bold text-[#2A2A2A]">{t(title)}</p><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-lg ${toneClass}`}><Icon aria-hidden="true" size={16} /></span></div><p className="mt-3 text-3xl font-extrabold tracking-tight text-[#111111]">{formatNumber(value)}</p><p className="mt-2 text-[11px] font-medium text-[#666666]">{detail}</p></article>;
}

export function MenuViewsChart({ points, total, period, days, onDaysChange }) {
  const { t } = useTranslation();

  const max = Math.max(0, ...points.map((item) => Number(item.views || 0)));
  return <section className="min-w-0 rounded-[18px] bg-[#111111] px-5 py-[22px] text-[#FFFDF5]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">{t("Vistas de tus menús")}</h2><p className="mt-1 text-[11px] text-[#D9D9D9]">{period}</p></div><label className="text-xs font-semibold"><span className="sr-only">{t("Periodo de la gráfica")}</span><select value={days} onChange={(event) => onDaysChange(Number(event.target.value))} className="min-h-11 cursor-pointer rounded-lg border border-white/15 bg-[#2A2A2A] px-3 text-[#FFFDF5] outline-none focus:ring-2 focus:ring-[#FFE05A]"><option value={7}>{t("7 días")}</option><option value={30}>{t("30 días")}</option></select></label></div><p className="mt-4 text-4xl font-extrabold text-[#FFE05A]">{formatNumber(total)}</p><div role="img" aria-label={`Gráfica de vistas. Total: ${total}. ${points.map((point) => `${point.date}: ${point.views}`).join(", ")}`} className="mt-5 flex min-h-52 items-end gap-2 sm:gap-4">{points.length ? points.map((point, index) => { const value = Number(point.views || 0); const isMax = max > 0 && value === max; const height = max > 0 ? Math.max(4, value * 100 / max) : 3; return <div key={point.date} className="flex min-w-0 flex-1 flex-col items-center justify-end gap-2"><span className="sr-only">{value} vistas{isMax ? t(", valor máximo") : ""}</span><div title={`${point.date}: ${value} vistas`} className={`w-full max-w-16 rounded-lg ${isMax ? "bg-[#FFE05A]" : "bg-[#2A2A2A]"}`} style={{ height: `${height}%`, minHeight: "4px" }} /><span className="truncate text-[10px] capitalize text-[#D9D9D9]">{point.label}{points.length <= 7 && <span className="hidden sm:inline"> {safeDay(point.date)}</span>}</span><span className="sr-only">{t("Posición")} {index + 1}</span></div>; }) : <p className="m-auto text-center text-sm text-[#D9D9D9]">{t("Todavía no hay vistas en este periodo.")}</p>}</div></section>;
}

function safeDay(date) { return date?.slice(8, 10) || ""; }

function ActionContent({ icon: Icon, title, description }) { return <><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-[9px] bg-[#FFE05A]"><Icon aria-hidden="true" size={18} /></span><span className="min-w-0 text-left"><span className="block text-xs font-bold">{title}</span><span className="mt-0.5 block text-[10px] text-[#555555]">{description}</span></span></>; }

export function QuickActions({ businessId, catalogueId, onCreateMenu }) {
  const { t } = useTranslation();

  const base = catalogueId ? `/dashboard/businesses/${businessId}/catalogues/${catalogueId}` : null;
  const disabledReason = t("Selecciona o crea un menú para utilizar esta acción.");
  return <section className="rounded-[18px] bg-[#F8E8AE] px-5 py-[22px]"><h2 className="text-base font-bold">{t("Acciones rápidas")}</h2><p className="mt-1 text-[11px] text-[#555555]">{t("Administra tu contenido sin perder tiempo.")}</p><div className="mt-4 grid gap-3"><button type="button" onClick={onCreateMenu} disabled={!businessId} title={!businessId ? t("Selecciona o crea un negocio primero.") : undefined} className="flex min-h-[62px] cursor-pointer items-center gap-3 rounded-xl bg-[#FFFDF5] p-3 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#111111] disabled:cursor-not-allowed disabled:opacity-50"><ActionContent icon={Plus} title={t("Nuevo menú")} description={t("Crea una nueva plantilla")} /></button>{base ? <Link to={`${base}/products`} className="flex min-h-[62px] cursor-pointer items-center gap-3 rounded-xl bg-[#FFFDF5] p-3 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#111111]"><ActionContent icon={PackagePlus} title={t("Agregar producto")} description={t("Añádelo a tu catálogo")} /></Link> : <DisabledAction icon={PackagePlus} title={t("Agregar producto")} description={t("Añádelo a tu catálogo")} reason={disabledReason} />}{base ? <Link to={`${base}/qr`} className="flex min-h-[62px] cursor-pointer items-center gap-3 rounded-xl bg-[#FFFDF5] p-3 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#111111]"><ActionContent icon={QrCode} title={t("Descargar QR")} description={t("Comparte tu menú")} /></Link> : <DisabledAction icon={QrCode} title={t("Descargar QR")} description={t("Comparte tu menú")} reason={disabledReason} />}{base ? <Link to={`${base}/analytics`} className="flex min-h-[62px] cursor-pointer items-center gap-3 rounded-xl bg-[#FFFDF5] p-3 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#111111]"><ActionContent icon={BarChart3} title={t("Ver analíticas")} description={t("Revisa el rendimiento")} /></Link> : <DisabledAction icon={BarChart3} title={t("Ver analíticas")} description={t("Revisa el rendimiento")} reason={disabledReason} />}</div></section>;
}

function DisabledAction({ reason, ...content }) { return <button type="button" disabled title={reason} aria-label={`${content.title}. ${reason}`} className="flex min-h-[62px] cursor-not-allowed items-center gap-3 rounded-xl bg-[#FFFDF5] p-3 opacity-55"><ActionContent {...content} /></button>; }

export function ActiveMenus({ menus, businessId, onCreateMenu }) {
  const { t } = useTranslation();

  return <section className="rounded-2xl border border-[#D9D9D9] bg-[#FFFDF5] p-5"><div className="flex items-center justify-between gap-3"><h2 className="text-base font-bold">{t("Menús activos")}</h2>{businessId && <Link to={`/dashboard/businesses/${businessId}/catalogues`} className="min-h-11 cursor-pointer py-3 text-xs font-bold text-[#A98D15] hover:underline">{t("Ver todos →")}</Link>}</div>{menus.length ? <div className="mt-2 divide-y divide-[#E9DDB7]">{menus.map((menu) => <Link key={menu.id} to={`/dashboard/businesses/${businessId}/catalogues/${menu.id}`} state={{ catalogue: menu }} className="flex min-h-16 cursor-pointer items-center gap-3 px-2 py-3 focus-visible:outline-2 focus-visible:outline-[#E8C93D]"><span aria-hidden="true" className={`h-2.5 w-2.5 shrink-0 rounded-full ${menu.is_published ? "bg-[#FFE05A]" : "bg-[#D9D9D9]"}`} /><span className="min-w-0 flex-1"><span className="block truncate text-xs font-bold">{menu.name}</span><span className="mt-0.5 block text-[10px] text-[#666666]">{menu.productCount === null ? t("Productos sin información") : `${menu.productCount} productos`}</span></span><span className="rounded-lg px-2 py-1 text-[10px] font-bold">{menu.is_published ? "Publicado" : "Borrador"}</span><span className="hidden text-[10px] text-[#555555] sm:block">{menu.views === null ? t("Vistas no disponibles") : `${formatNumber(menu.views)} vistas`}</span></Link>)}</div> : <div className="py-10 text-center"><BookOpen aria-hidden="true" className="mx-auto text-[#8A7420]" /><p className="mt-3 text-sm font-semibold">{t("Todavía no tienes menús.")}</p><button type="button" onClick={onCreateMenu} className="mt-4 min-h-11 cursor-pointer rounded-xl bg-[#FFE05A] px-4 font-bold">{t("Crear el primero")}</button></div>}</section>;
}

export function RecentActivity() {
  const { t } = useTranslation();
 return <section className="rounded-2xl bg-[#2A2A2A] p-5 text-[#FFFDF5]"><h2 className="text-base font-bold">{t("Actividad reciente")}</h2><div className="mt-8 text-center"><span className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-[#FFE05A] text-[#111111]"><Box aria-hidden="true" size={18} /></span><p className="mt-3 text-sm font-semibold">{t("Todavía no hay actividad reciente.")}</p><p className="mt-1 text-[11px] text-[#D9D9D9]">{t("Esta sección se conectará cuando exista un historial de actividad.")}</p></div></section>; }

export function DashboardSkeleton() {
  const { t } = useTranslation();
 return <div aria-label={t("Cargando resumen del dashboard")} aria-live="polite" className="space-y-6"><div className="h-20 animate-pulse rounded-xl bg-white" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[0, 1, 2, 3].map((item) => <div key={item} className="h-36 animate-pulse rounded-2xl bg-white" />)}</div><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(280px,376px)]"><div className="h-96 animate-pulse rounded-[18px] bg-[#2A2A2A]" /><div className="h-96 animate-pulse rounded-[18px] bg-[#F8E8AE]" /></div></div>; }
